repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
      args:
        - --in-place
        - --recursive
        - --aggressive
        - --experimental
        - --max-line-length=130
        - --verbose
        - launchable/
        - tests/
