openapi: 3.0.0
info:
  title: Launchable API
  version: '1.0'
  description: A description of the *Launchable API*
  license:
    name: 'The Apache License, Version 2.0.'
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  termsOfService: 'https://www.launchableinc.com/'
  contact:
    email: info@launchableinc.com
    url: 'https://www.launchableinc.com/contact'
    name: 'Launchable, Inc. '
servers:
  - url: 'http://localhost:8080'
    description: development
paths:
  '/organizations/{organization}/workspaces/{workspace}/commits/collect':
    parameters:
      - schema:
          type: string
        name: organization
        in: path
        required: true
        description: organization name
      - schema:
          type: string
        name: workspace
        in: path
        required: true
        description: workspace name
    post:
      summary: Collect commit data
      responses:
        '201':
          description: OK
      operationId: post-organizations-organization-workspaces-workspace-commits-collect
      description: Collect commit data endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                commits:
                  type: array
                  items:
                    $ref: '#/components/schemas/commit'
              required:
                - commits
            examples:
              Example:
                value:
                  commits:
                    - commitHash: commit_hash_3
                      authorName: Yoshiori Shoji
                      authorEmailAddress: yshoji@launcableinc.com
                      authorWhen: 1561744815000
                      authorTimezoneOffset: 540
                      committerName: Yoshiori Shoji
                      committerEmailAddress: yshoji@launcableinc.com
                      committerWhen: 1561744815000
                      committerTimezoneOffset: 540
                      message: add files
                      parentHashes:
                        commit_hash_1:
                          - linesAdded: 0
                            linesDeleted: 100
                            status: M
                            path: path_1
                            pathTo: path_1
                          - linesAdded: 10
                            linesDeleted: 0
                            status: M
                            path: path_2
                            pathTo: path_2
                        commit_hash_2:
                          - linesAdded: 0
                            linesDeleted: 100
                            status: M
                            path: path_1
                            pathTo: path_1
                    - commitHash: commit_hash_4
                      authorName: Yoshiori Shoji
                      authorEmailAddress: yshoji@launcableinc.com
                      authorWhen: 1561744817000
                      authorTimezoneOffset: 540
                      committerName: Yoshiori Shoji
                      committerEmailAddress: yshoji@launcableinc.com
                      committerWhen: 1561744817000
                      committerTimezoneOffset: 540
                      message: modify
                      parentHashes:
                        commit_hash_2:
                          - linesAdded: 0
                            linesDeleted: 100
                            status: M
                            path: path_2
                            pathTo: path_2
        description: ''
      parameters: []
      tags:
        - commit
  '/organizations/{organization}/workspaces/{workspace}/commits/latest':
    parameters:
      - schema:
          type: string
        name: organization
        in: path
        required: true
        description: Organization name
      - schema:
          type: string
        name: workspace
        in: path
        required: true
        description: Workspace name
    get:
      summary: All the head commits
      tags:
        - commit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: all the head commits.
                items:
                  type: string
              examples:
                example:
                  value:
                    - commit_hash1
                    - commit_hash2
      operationId: get-organizations-organization-workspaces-workspace-commits-latest
      description: Returns all the head commits that collectively represents the commit graph that the server currently possesses.
  '/organizations/{organization}/workspaces/{workspace}/inference':
    parameters:
      - schema:
          type: string
        name: organization
        in: path
        required: true
      - schema:
          type: string
        name: workspace
        in: path
        required: true
    post:
      summary: ''
      operationId: post-organizations-organization-workspaces-workspace-inference
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tree'
      description: Returns optimized test execution order.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  $ref: '#/components/schemas/tree'
                session:
                  $ref: '#/components/schemas/test-session'
              required:
                - test
                - session
components:
  schemas:
    commit:
      title: commit
      type: object
      description: Commit data
      x-tags:
        - commit
      properties:
        commitHash:
          type: string
        authorName:
          type: string
          description: Person who wrote the actual change.
        authorEmailAddress:
          type: string
          description: Email address of authorName.
        authorWhen:
          type: number
          description: 'Timestamp of the commit in Unix time, measured in ms.'
        authorTimezoneOffset:
          type: integer
          description: |-
            Time zone offset in minutes.
            For example, JST is +9:00 so this field is 540.
        committerName:
          type: string
          description: Person who received the change and integrated it into the commit tree.
        committerEmailAddress:
          type: string
          description: Email address of committerName.
        committerWhen:
          type: number
          description: 'Timestamp of the commit in Unix time, measured in ms.'
        committerTimezoneOffset:
          type: integer
          description: |-
            Time zone offset in minutes.
            For example, JST is +9:00 so this field is 540.
        message:
          type: string
          description: Commit message.
        parentHashes:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/file-change'
          description: 'An array of file changes, keyed by the parent commithash'
      required:
        - commitHash
        - authorName
        - authorEmailAddress
        - authorWhen
        - authorTimezoneOffset
        - committerName
        - committerEmailAddress
        - committerWhen
        - committerTimezoneOffset
        - message
        - parentHashes
    file-change:
      title: File Change
      type: object
      x-examples: {}
      description: Delta between this commit and its parent.
      x-tags:
        - commit
      properties:
        linesAdded:
          type: integer
          description: Number of lines added.
        linesDeleted:
          type: integer
          description: Number of lines removed.
        status:
          type: string
          description: |-
            File status marker, like 'M', 'A', 'D' that represents the operation.
            "R" (rename) and "C" (copy) are special case because they are accompanied by the confidence level, such as "R100".
        path:
          type: string
          description: |-
            Get the old name associated with this file.

            The meaning of the old name can differ depending on the semantic meaning of this patch:

            - *file add*: always `/dev/null`
            - *file modify*: always pathTo
            - *file delete*: always the file being deleted
            - *file copy*: source file the copy originates from
            - *file rename*: source file the rename originates from
        pathTo:
          type: string
          description: |-
            Get the new name associated with this file.

            The meaning of the new name can differ depending on the semantic meaning of this patch:

            - *file add*: always the file being created
            - *file modify*: always path
            - *file delete*: always  `/dev/null`
            - *file copy*: destination file the copy ends up at
            - *file rename*: destination file the rename ends up at
      required:
        - linesAdded
        - linesDeleted
        - status
        - path
        - pathTo
    tree:
      title: tree
      type: object
      description: 'A tree representation of a test execution plan. Non-leaf nodes correspond to a unit of reordering and leaf nodes correspond to each test case. '
      properties:
        root:
          oneOf:
            - $ref: '#/components/schemas/tree-node'
            - $ref: '#/components/schemas/test-case-node'
          description: A reference to a root node of the tree.
        type:
          type: string
          description: An objec type. Type needs to be 'tree'.
      required:
        - root
        - type
    tree-node:
      title: tree-node
      type: object
      description: 'A non-leaf node of a tree and a unit of reordering, which usually corresponds to module, class, or file.'
      properties:
        id:
          type: string
          description: 'Arbitrary string, which identifies each tree-node and helps a client to reorder tests more easily'
        children:
          oneOf:
            - $ref: '#/components/schemas/tree-node'
            - $ref: '#/components/schemas/test-case-node'
          description: A list of child nodes.
        type:
          type: string
          description: An objec type. Type needs to be 'treeNode'.
      required:
        - children
    test-case-node:
      title: test-case-node
      type: object
      properties:
        testName:
          type: string
          description: 'A name of the test case, which identifies each tests. '
        type:
          type: string
          description: An objec type. Type needs to be 'testCaseNode'.
      required:
        - testName
        - type
      description: 'A leaf node of a tree, which corresponds to an actual test case'
    test-session:
      title: test-session
      type: object
      description: Represents an execution of a group of tests against a single subject.
      properties:
        subject:
          type: string
          description: Foreign key to SubjectUnderTest id.
        id:
          type: string
          description: Unique identifier of this test session.
        flavors:
          description: The same test can be run against the same build with different parameters. We generalize this notion to 'flavors' where key/value pairs collectively uniquely specify the configuration. What those keys and values mean are up to users. We treat them as opaque strings.
          type: object
          additionalProperties:
            type: string
      required:
        - subject
        - id
  securitySchemes:
    LAUNCHABLE_TOKEN:
      type: http
      scheme: bearer
tags:
  - name: commit
security:
  - LAUNCHABLE_TOKEN: []
